version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: album-app-postgres-dev
    environment:
      POSTGRES_DB: albumapp
      POSTGRES_USER: albumuser
      POSTGRES_PASSWORD: albumpass
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ASP.NET Core Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: album-app-backend-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=localhost;Database=albumapp;Username=albumuser;Password=albumpass
    network_mode: host
    volumes:
      - ./backend:/app
      - ./data/pict:/data/pict
      - ./data/thumb:/data/thumb
      - /app/bin
      - /app/obj
    depends_on:
      - postgres
    restart: unless-stopped

  # Angular Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: album-app-frontend-dev
    environment:
      - NODE_ENV=development
    network_mode: host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

# Using host network mode for all services